### PR TITLE
added lombok

### PR DESCRIPTION
**Pull request by vcharmcaster**
simplified code base via adding lombok

### CODE REVIEW

**Comment by vcharmcaster** [comment]
> @vcharmcaster please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by jdubois** [comment]
I’m sorry, but we can’t have Lombok on the sample app.
We need something that works well across all JDKs, GraalVM, and IDEs. For example, we can’t have people “git clone" the project and get errors because there IDE doesn’t have the plug in (or worse, because there is no plug in for their IDE).

**Comment by vcharmcaster** [comment]
> I’m sorry, but we can’t have Lombok on the sample app. We need something that works well across all JDKs, GraalVM, and IDEs. For example, we can’t have people “git clone" the project and get errors because there IDE doesn’t have the plug in (or worse, because there is no plug in for their IDE).

Thank you for explanation, closing PR.

**Comment by jdubois** [comment]
Yes, and super sorry about this - you should have pinged me first, so we discussed it! I hate to do this...

**Pull request closed without merging**
